version: '3.8'

services:
  maxishop_backend:
    container_name: maxishop_backend
    image: maxishop_backend
    build: 
      context: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - PGDATABASE=maxishop_db
      - PGUSER=eric
      - PGPASSWORD=12345
      - PGHOST=maxishop_db
    depends_on:
      - maxishop_db
  maxishop_db:
    container_name: maxishop_db
    image: 'postgres:12'
    ports: 
      - '5342:5342'
    environment: 
      - POSTGRES_USER=eric
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=maxishop_db
    volumes:
      - nps_data:/var/lib/postgresql/data
  maxishop_pgadmin:
    container_name: maxishop_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"


volumes:
  nps_data: {}